// Generated by CoffeeScript 1.6.3
(function() {
  var async, cleanFiles, coffeescript, compileFileType, compileFiles, copyStaticFiles, fs, less, path, spawn, utils, _;

  fs = require('fs');

  path = require('path');

  async = require('async');

  _ = require('underscore');

  spawn = require('child_process').spawn;

  coffeescript = require('coffee-script');

  less = require('less');

  compileFileType = require('./compile-file-type');

  utils = require('./utils');

  exports.build_pre_compile = function(logger, config, cli, build, finished) {
    var projectDir, resourcesOutputDir;
    projectDir = build.projectDir || process.cwd();
    logger.info("Compiling source files at: " + projectDir);
    logger.debug(build);
    resourcesOutputDir = projectDir + '/Resources';
    return async.parallel([
      function(cb) {
        var err;
        try {
          fs.mkdirSync(resourcesOutputDir);
        } catch (_error) {
          err = _error;
          if (!err || err.code !== 'EEXIST') {
            return cb(err);
          }
        }
        return cb(null);
      }, function(cb) {
        return compileFiles(logger, resourcesOutputDir, resourcesOutputDir, cb);
      }
    ], function(err) {
      if (err) {
        logger.error("Error compiling files: " + err);
        throw err;
      }
      logger.info('Finished compiling source files');
      return finished();
    });
  };

  exports.clean_post = function(logger, config, cli, build, finished) {
    var resourcesOutputDir;
    console.log(cli.argv['project-dir']);
    resourcesOutputDir = cli.argv['project-dir'] + '/Resources';
    logger.info("Cleaning resources output directory: " + resourcesOutputDir);
    return cleanFiles(resourcesOutputDir);
  };

  copyStaticFiles = function(inputDir, outputDir, cb) {
    spawn('cp', ['-r', inputDir + '/', outputDir]);
    return cb(null);
  };

  compileFiles = function(logger, inputDir, outputDir, cb) {
    var compileFunctions;
    compileFunctions = _.map([
      {
        inSuffix: 'coffee',
        outSuffix: 'js',
        fnCompile: utils.funcAsAsync(coffeescript.compile)
      }, {
        inSuffix: 'less',
        outSuffix: 'css',
        fnCompile: less.render
      }
    ], function(funcDef) {
      return function(cbCompile) {
        return compileFileType(logger, funcDef.fnCompile, inputDir, funcDef.inSuffix, outputDir, funcDef.outSuffix, cbCompile);
      };
    });
    return async.parallel(compileFunctions, function(err) {
      return cb(err);
    });
  };

  cleanFiles = function(outputDir, cb) {
    return spawn('rm', ['-r', outputDir + path.sep]);
  };

}).call(this);
